# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
